name: Update Snapshots
on:
    workflow_dispatch:

permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push
    contents: write

env:
    NODEJS_VERSION: 20

jobs:
  set_job_params:
    name: Set Job Params
    runs-on: ubuntu-latest
    outputs:
      pw-version: ${{ steps.set_version.outputs.PW_VERSION }}
    steps:
      - uses: actions/checkout@v4
              
      - name: Yarn Install
        run: yarn install --mode=skip-build

      - name: Get Playwright Package Version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3.1
        with:
          path: node_modules/playwright

      - name: Set Package Version
        id: set_version
        run: echo "PW_VERSION=${{ steps.get-version.outputs.version }}" >> $GITHUB_OUTPUT

  update_snapshots:
    name: Update Snapshots
    needs: set_job_params
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.set_job_params.outputs.pw-version }}-jammy

    steps:
    - uses: actions/checkout@v4

    - name: Yarn Install
      run: yarn install

    - name: Update Snapshots
      run: yarn test --grep snapshot --update-snapshots --reporter=list
      env:
        HOME: /root # required for playwright to run in container

    - name: Commit and Push Snapshots
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: Update Playwright Snapshots
        file_pattern: "tests/visual/*.png"